### ISSUE TITLE
 Request to Remove node_modules from Repository

### ISSUE THREAD

**Issue by griga** [ivopc/phaser-lpc-character#1]
Hello,

I noticed that the `node_modules` directory is currently being tracked in the repository. This directory is typically not included in version control as it can be quite large and can easily be recreated by running `npm install` or `yarn install` after cloning the repository.

Including `node_modules` in the repository can lead to conflicts between developers' environments and can make the repository unnecessarily large and slow to clone.

I propose to remove the `node_modules` directory from the repository.

Run the following commands to remove the `node_modules` directory from the repository:

```bash
git rm -r --cached node_modules
git commit -m "Remove node_modules from repository"
git push
```

**Comment by ivopc** [comment]
@griga hey thank you for the advice that I did not noticed. It's just weird because the `node_modules` is inside of `.gitignore`
